### ISSUE TITLE
Can't compile Mumble slice

### ISSUE THREAD

**Issue by UndeRus** [cemoktra/ice-rs#49]
Can't compile this https://github.com/mumble-voip/mumble/blob/master/src/murmur/Murmur.ice slice at least because of 2 reasons:

- Multiline comments
- Includes with nested paths

**Comment by cemoktra** [comment]
Hi,

at least i know about the nested path problem, but i stopped work here cause the company i'm working for is moving away from ice completely. So i do not invest more time here, but feel free to create a PR, i will look into this
